### ISSUE TITLE
Weird state when using registers in insert mode

### ISSUE THREAD

**Issue by jsongerber** [jake-stewart/multicursor.nvim#10]
When using registers in insert mode (`<c-r>`) we then can't exit insert mode, `<esc>` is not working. The cursor is the shape of normal mode, but any key entered is inserted in the buffer. The only solution to exit is to use `<c-c>`.

**Comment by jake-stewart** [comment]
works for me. have you tried disabling plugins?

**Comment by jsongerber** [comment]
I didn't I will try with a clean config and only your plugin, I'll report back (probably not before tomorrow)

**Comment by jake-stewart** [comment]
no rush. it's bed time for me anyway

**Comment by jake-stewart** [comment]
i managed to reproduce

**Comment by jake-stewart** [comment]
should be fixed now. try `:Lazy update` and let me know

**Comment by mikavilpas** [comment]
I had some weird issues but they seem to be resolved. In my case, typing into a telescope search window would enter the first character correctly, but the second character would be entered before the previous character (not after it).

Pretty weird stuff. 🙂

**Comment by jake-stewart** [comment]
Closing as I assume it's fixed. Open a new issue if it persists for you.

**Comment by jsongerber** [comment]
Thank you, it's fixed!
