### ISSUE TITLE
cursorsEnabled always return true

### ISSUE THREAD

**Issue by jsongerber** [jake-stewart/multicursor.nvim#11]
Sorry to spam, I'll close nvim for today and should not bother you again :)
I'm trying to remap `]` and `[` to change cursor without loosing default behavior, to do this I have this code (simplified for readability):
```
vim.keymap.set({ 'n', 'v' }, ']', function()
  vim.print(vim.inspect(mc.cursorsEnabled()))
  if mc.cursorsEnabled() then
    mc.nextCursor()
  else
    -- Default behavior
  end
end)
```
but `cursorsEnabled` always return true, even when no other cursors have been added

**Comment by jake-stewart** [comment]
works for me.

`mc.cursorsEnabled()` is different from `mc.hasCursors()`. are you confusing the two? `mc.cursorsEnabled()` returns false when you have used `mc.disableCursors()`

**Comment by jsongerber** [comment]
Yes my bad, thank you I indeed didn't understand the difference
