### ISSUE TITLE
Visual selection issue.

### ISSUE THREAD

**Issue by octaviusz** [jake-stewart/multicursor.nvim#13]
When you try to visually select text with a tab indentation, the cursor jumps to the left corner. If the indentation is done with spaces, everything works fine. There is also a problem with text selection if enabled Lsp Inlay Hint.

**Comment by jake-stewart** [comment]
added to list of reasons why i hate tabs !!!!!

i will try fix today

**Comment by jake-stewart** [comment]
@octaviusz should be fixed now. try `:Lazy update`.

tabs still cause problems if you use `:h virtualedit`. you probably dont use it.
i thin the lsp inlay hint is fixed along with tabs (since the problem was to do with screen columns). let me know if there are any more issues

thanks

**Comment by octaviusz** [comment]
all good, thanks
