### ISSUE TITLE
API feedback

### ISSUE THREAD

**Issue by ajvondrak** [jake-stewart/multicursor.nvim#17]
I've been tinkering with getting the semantics/mappings I want, and I've run into some rough edges of the API, so I thought I'd share my experience report. The context here is that I want a single keybinding to toggle a virtual cursor at the current (main) cursor position.

I arrived at this implementation, which does what I want:

```lua
vim.keymap.set("n", "q", function()
  mc.action(function(ctx)
    ctx:setCursorsEnabled(false)
    local actual = ctx:mainCursor()
    local nearest = ctx:nearestCursor(actual:getPos())
    if nearest == actual then
      actual:clone()
    else
      nearest:delete()
    end
  end)
end)
```

But getting there unveiled a couple of oddities, or at least things that I personally found surprising:

1. With `setCursorsEnabled(false)`, `getCursors()` only returns `{ mainCursor() }`, even if there are virtual cursors in `state.cursors`. In general, I think the borders are fuzzy between the `state.mainCursor` and the same cursor as it exists in `state.cursors`.
2. Some methods of the API loop over `getCursors()` (`forEachCursor`, `mapCursors`, `findCursor`) while others loop over `state.cursors` directly (`nextCursor`, `prevCursor`, `nearestCursor`, `firstCursor`, `lastCursor`), leading to inconsistent outcomes depending on `state.enabled`.
3. `nearestCursor` happens to loop through `state.cursors`(though I can't be sure if it's on purpose), but returns `mainCursor()` as a default. As such, `nearest == actual` in the above implementation implies that there was either a virtual cursor at a different position or there were *no* virtual cursors. So this seems like an unstable/confusing way of asking "is there a virtual cursor at the current position?" Again, telling the difference between the main cursor and the virtual cursors seems to get fuzzy.
4. Once I've determined to add a virtual cursor, there's `mc.addCursor()`. But that's a high-level API defined as its own `action`, which means I can't call it from within *my* `mc.action`. Oops.
5. Thus I needed to figure out that the low-level API for adding a virtual cursor to the `CursorContext` is via the `Cursor:clone()` method, which pushes it into `state.cursors`. It makes some sort of internal sense I suppose, but I feel like I'd expect a `CursorContext:add()` method or something to that effect. It seems like there are gaps between what "goes" in the high-level API vs the low-level API.

Just figured a hallway usability test might give you food for thought as you continue shaping the API, for whatever it's worth. Appreciate your work!

**Comment by jake-stewart** [comment]
The Cursor API is not battle tested with real users yet. You are the first to give feedback, so thanks for the hard work.

1. Perhaps `getCursors()` should return all cursors, regardless of whether they are disabled, and it is up to the user to check `ctx:cursorsEnabled()`.

2. The above point would fix this.

3. I could add a `ctx:getCursorUnderMainCursor()` or something which returns the cursor at the current position, but not the main cursor since it's obviously always there.

4. I suppose we need a `ctx:addCursor()` which just calls `ctx:mainCursor():clone()` for the user.

5. If there are any other gaps, then I agree they should be added the same as 4.

**Comment by jake-stewart** [comment]
for simplicity, i'm thinking about adding `ctx:getCursorAtPos` which prioritises virtual cursors over the main cursor if multiple are on the same cell.

```lua
local cursor = ctx:getCursorAtPos(ctx:mainCursor():getPos())
if cursor ~= ctx:mainCursor() then
    cursor:delete()
end
```

**Comment by jake-stewart** [comment]
I have merged these new methods:

`ctx:overlappedCursor()`, `ctx:addCursor()`, and `ctx:getCursorAtPos()`

I have changed `ctx:getCursors()` so that it returns all cursors regardless of enabled state.

If you have more API feedback I'd love to hear it.

**Comment by ajvondrak** [comment]
Excellent, thanks for your quick turnaround! Really cleans up the spelling of my binding:

```lua
vim.keymap.set("n", "q", function()
  mc.action(function(ctx)
    ctx:setCursorsEnabled(false)
    local cursor = ctx:overlappedCursor()
    if cursor then
      cursor:delete()
    else
      ctx:addCursor()
    end
  end)
end)
```

Thinking out loud:

Now that there's the `ctx:addCursor()` method, I wondered about a symmetric `ctx:deleteCursor()`, then realized that that probably doesn't make sense. The main cursor might not be overlapping a virtual cursor, and you can't _really_ ever delete the main cursor, can you? 🤔 Or is there a situation where `ctx:mainCursor():delete()` makes any sense?

I just found it interesting that adding a simple `ctx:addCursor()` method started clearing up the distinction between the main cursor and the virtual cursors already. Or at least that's where my brain goes, haha. I'm thinking of the main cursor as technically having a separate type from the other virtual cursors, since some operations make sense on virtual cursors but not the real one. But that's admittedly just my half-baked musings.

I'll keep you posted about anything else I bump into as I continue hacking. Thanks again for your responsiveness!

**Comment by jake-stewart** [comment]
@ajvondrak I aim for the main cursor to behave exactly like any other cursor.

Deleting the main cursor is perfectly valid. If the main cursor is deleted then the nearest cursor is automatically selected (or a new one is created if none exist).

**Comment by ajvondrak** [comment]
Ah, I see. Interesting. So maybe a symmetric `ctx:deleteCursor()` is appropriate too. Not that I've run into the need yet, if you couldn't tell. 😛 Baby steps!

**Comment by ajvondrak** [comment]
Which I mention because I could imagine the definition being like

```lua
vim.keymap.set("n", "q", function()
  mc.action(function(ctx)
    ctx:setCursorsEnabled(false)
    if ctx:overlappedCursor() then
      ctx:deleteCursor()
    else
      ctx:addCursor()
    end
  end)
end)
```

Just as far as golfing goes. But just the changes you've made already have already cleaned things up nicely. 👍

**Comment by jake-stewart** [comment]
@ajvondrak I think I prefer `ctx:overlappedCursor:delete()` because it's not obvious what `ctx:deleteCursor()` is deleting. Meanwhile `ctx:addCursor()` is fine since it doesn't matter where the cursor is added (You can `ctx:addCursor():setPos()`) and is less specific than `ctx:mainCursor():clone()`. Thanks for all the ideas though.

**Comment by ajvondrak** [comment]
Yeah, that's a good point. Shows how my own train of thought went `ctx:deleteCursor()` -> "I guess that deletes the main cursor" -> "does deleting the main cursor make sense?" I agree it's generally clearer to call `Cursor:delete()` where you want, whereas `Cursor:clone()` is _technically_ how "adding" a cursor works, but `CursorContext:addCursor()` is easier to grok.
