### ISSUE TITLE
How to manage hlsearch?

### ISSUE THREAD

**Issue by unphased** [jake-stewart/multicursor.nvim#19]
looks like my Search highlight overrides the highlight that i have set for multicursor. This means when I use the `mc.addCursor("*")` behavior since that assigns the search buffer (which i dont have a problem with), it will cause my Search highlight to appear due to `hlsearch` being on, and cause the cursor bgcolor to get hidden behind the word. 

I guess for this particular problem I would want to just make a call to `set nohlsearch` alongside `mc.addCursor("*")`. In fact that will solve this problem. But I wonder if anyone has some tricks for managing the issue of different features from different plugins conflicting in bgcolor assignments. For example in addition to hlsearch's `Search` highlight group, I also have the gitsigns plugin manipulating some bgcolors. I guess [there is just no solution](https://vi.stackexchange.com/questions/41420/in-neovim-is-there-a-way-at-nvim-level-to-set-priorities-to-control-highlight-re) for assigning priorities to neovim highlights still.

**Comment by jake-stewart** [comment]
Could perhaps automatically disable hlsearch when using multicursor, then enable it once it's done? With an option to turn off this behaviour.

**Comment by unphased** [comment]
Yeah i already got this working well, since the way you've designed the maps i can just manipulate hlsearch as necessary in the functions.

**Comment by jake-stewart** [comment]
I think it would be nice to have some kind of hlsearch handling built into the plugin.

I will ponder this when I have time.

**Comment by jake-stewart** [comment]
`hlsearch` is now disabled when multiple cursors are activated and automatically restored.

**Comment by unphased** [comment]
Awesome! Thanks.
