### ISSUE TITLE
Statusline integration

### ISSUE THREAD

**Issue by unphased** [jake-stewart/multicursor.nvim#20]
I think this is the first multicursor plugin that is worth using in (n)vim for me and that's a big deal because i have a LOT of small features I have hacked around out of different approaches that can be potentially better addressed via multiple cursors. 

One thing I noticed (and that we all really like) about this multicursor plugin is that you can actually do vim motions and manipulations and enter and exit visual mode when multiple cursors are active. It's insanely powerful and makes all the capabilities we set up in vim more powerful. it seems to even work with other plugins that modify behavior (e.g. spider which i use, the individual multicursors correctly word-hop and i didn't need to integrate anything). 

As a result though it looks like we now stack on 2 more states, multicursor mode, and multicursor visual mode, and we use `<esc>` to exit them, that is to say if we end up in multicursor visual mode i have to hit esc 2 times to return to normal mode. 

Sometimes it's possible to end up with cursors that are not in view and depending on what we configured for highlight it may be hard to see them. Even though it is possible to have binds to cycle the focused cursor around the set of multicursors i would definitely want to integrate the multicursor mode state into my statusline/bufbar/etc. 

So I reckon I would just require('multicursor-nvim') from heirline config to do that... An example would be great though!

**Comment by jake-stewart** [comment]
I'm not sure how status lines know when to update. I might need to add some sort of mode change event. For the time being you can use `mc.hasCursors()` to check whether virtual cursors exist, and then use `vim.fn.mode()` like you normally would. Visual cursor char mode = `mc.hasCursors()` and `vim.fn.mode() == "v"`

I'll play with this when I have time and put a working config in the readme somewhere.

**Comment by rootiest** [comment]
I threw together a basic little statusline function:

```lua
---@function Function to render the MultiCursor statusline
---@return table status The MultiCursor status object
local function .mc_statusline()
  local mc = require("multicursor-nvim")
  local status = {}
  if mc.hasCursors() then
    status.enabled = true
    if vim.fn.mode() == "v" then
      status.icon = "󰚕 "
      status.short_text = "V"
      status.text = "VISUAL"
      status.color = "lualine_a_visual"
    else
      status.icon = "󰬸 "
      status.short_text = "N"
      status.text = "NORMAL"
      status.color = "lualine_a_normal"
    end
  else
    status.enabled = false
    status.icon = "󰘪 "
    status.short_text = "NO"
    status.text = "SINGLE"
    status.color = "lualine_a_normal"
  end
  status.icon_short_text = status.icon .. status.short_text
  status.icon_text = status.icon .. status.text
  return status
end
```

which I use in my lualine_a section after the mode:

```
{ -- MultiCursors
  function()
    return mc_statusline().icon
  end,
  cond = function()
    return mc_statusline().enabled
  end,
  color = function()
    return mc_statusline().color
  end,
  padding = { left = 0, right = 0 },
  separator = { left = "", right = "" },
}
```

if anyone wants something basic to start with

![image](https://github.com/user-attachments/assets/0a0c559b-3a74-4fca-842c-fea5c7d1b514)

![image](https://github.com/user-attachments/assets/a90f8844-3c1b-405f-b595-2c5e140d60f0)

**Comment by jake-stewart** [comment]
```lua
function CustomStatuslineFunction()
    local mc = require("multicursor-nvim")
    if mc.hasCursors() then
        local enabled = mc.numEnabledCursors()
        local disabled = mc.numDisabledCursors()
        return enabled .. " Cursor" .. (enabled == 1 and "" or "s")
            .. (disabled == 0 and "" or " [" .. disabled .. " disabled]")
    else
        return "multicursor inactive"
    end
end

vim.o.laststatus = 2
vim.o.statusline = "%{v:lua.CustomStatuslineFunction()}"
```

added `mc.numCursors()`, `mc.numEnabledCursors()` and `mc.numDisabledCursors()` which you can integrate into any statusline as shown above, or should be easy to integrate into any statusline plugin.

**Comment by jake-stewart** [comment]
I don't think I'll bother adding an example statusline to the readme. The new signs means people don't need anything in their statuslines. I'll update the doc with these new functions though.

**Comment by unphased** [comment]
Sweet! The signs are nice, can be easily configured to be as visually salient as desired, and provide a LOT more information on cursor positioning compared to anything that can be done in the status line. Awesome.

**Comment by jake-stewart** [comment]
Not a bad idea. I will open a new issue

**Comment by jake-stewart** [comment]
> Not a bad idea. I will open a new issue

all done
