### ISSUE TITLE
Setting a colorscheme loses mutli cursor highlights

### ISSUE THREAD

**Issue by Napam** [jake-stewart/multicursor.nvim#21]
Here the following config I have for setting the colorscheme

```lua

vim.cmd([[
    au ColorScheme * hi Normal ctermbg=none guibg=none
    au ColorScheme * hi SignColumn ctermbg=none guibg=none
    au ColorScheme * hi NormalNC ctermbg=none guibg=none
    au ColorScheme * hi MsgArea ctermbg=none guibg=none
    au ColorScheme * hi TelescopeBorder ctermbg=none guibg=none
    au ColorScheme * hi NvimTreeNormal ctermbg=none guibg=none
    au ColorScheme * hi NvimTreeEndOfBuffer ctermbg=none guibg=none
]])

vim.cmd("colorscheme sonokai")
```

The plugin works! I can do multicursor editing and whatnot, but I can't see the cursors. To fix this I can simply comment out the `vim.cmd("colorscheme sonokai")`, then and I can see the mutliple cursors. So it was natural for me to think that there was something wrong with the sonokai colorscheme. So I tried others were available, and all of them caused multicursor highlight to disappear. This also happened on the default colorscheme, that is if my config was only `vim.cmd("colorscheme default")`, I can't see the cursors.

I also tried to remove all the colorscheme autocommands but it didn't seem to help.

**Comment by jake-stewart** [comment]
thanks, it should be fixed now. try `:Lazy update`

**Comment by Napam** [comment]
Thank you very much for the quick fix! It works now after updating! :) Great plugin by the way! I instantly switched from vim-visual-multi after seeing your reddit post saying that this one does not try to re-implement vim commands. And indeed this one feels more natural to use! It feels just like, well, regular vim, but with multicursors! Amazing work!
