### ISSUE TITLE
Cursor rotation with `setCursorsEnabled(false)`

### ISSUE THREAD

**Issue by ajvondrak** [jake-stewart/multicursor.nvim#24]
This post is kind of a follow-up to #17's discussion about API consistency. I was playing around with the top-level `{prev,next,first,last}Cursor` actions from examples.lua, but was puzzled at the behavior in light of our discussion about how the main cursor is supposed to behave like all the others.

### Setup

With the following config:

```lua
return {
  "jake-stewart/multicursor.nvim",
  branch = "1.0",
  config = function()
    local mc = require("multicursor-nvim")

    mc.setup()

    vim.keymap.set("n", "<c-q>", function()
      if mc.cursorsEnabled() then
        mc.disableCursors()
      else
        mc.addCursor()
      end
    end)

    vim.keymap.set("n", "<left>", mc.prevCursor)
    vim.keymap.set("n", "<right>", mc.nextCursor)
    vim.keymap.set("n", "<up>", mc.firstCursor)
    vim.keymap.set("n", "<down>", mc.lastCursor)

    vim.keymap.set("n", "<esc>", function()
      if not mc.cursorsEnabled() then
        mc.enableCursors()
      elseif mc.hasCursors() then
        mc.clearCursors()
      else
        -- Default <esc> handler.
      end
    end)

    vim.api.nvim_create_autocmd("ColorScheme", {
      callback = function()
        vim.api.nvim_set_hl(0, "MultiCursorCursor", { link = "Cursor" })
        vim.api.nvim_set_hl(0, "MultiCursorVisual", { link = "Visual" })
        vim.api.nvim_set_hl(0, "MultiCursorDisabledCursor", { link = "Visual" })
        vim.api.nvim_set_hl(0, "MultiCursorDisabledVisual", { link = "Visual" })
      end,
    })
  end,
}
```

Editing the following text:

```
Line 1
Line 2
Line 3
Line 4
Line 5
```

### Scenario 1: Cursor rotation itself

1. Navigate to the `1`, use `<c-q>` to add a cursor
2. Navigate to the `3`, use `<c-q>` to add a cursor
3. Navigate to the `5`, but do **not** add a cursor
4. If you press `<up>` (`mc.firstCursor`), `<left>` (`mc.prevCursor`), or `<right>` (`mc.nextCursor`), the main cursor moves to the expected position, but adds a virtual cursor at the `5` (where the main cursor previously was)
5. If you instead press `<down>` (`mc.lastCursor`), the main cursor does not move

I could see how this might be intentional. You could argue that navigation is "saving the place" of the previous main cursor. If the main cursor really is like all the rest, then these `<up>`/`<down>`/`<left>`/`<right>` bindings are just cycling through 3 cursors total (the main one + 2 virtuals). This also explains the behavior of `<down>`, since the main cursor is itself the last cursor.

### Scenario 2: Enabling cursors after moving

However, after navigating through cursors with these motions, the behavior of `<esc>` seems to contradict that philosophy.

As before:

1. Navigate to the `1`, use `<c-q>` to add a cursor
2. Navigate to the `3`, use `<c-q>` to add a cursor
3. Navigate to the `5`, but do **not** add a cursor

Now there are four possibilties based on how we navigate cursors. The punchline is that wherever we land in any direction, hitting `<esc>` proceeds to delete the cursor at that position.

- `<up>` (`mc.firstCursor`): moves the main cursor to `1` and leaves a virtual cursor at `5` (the prior position). `<esc>` then moves the main cursor to `3`, which is enabled along with cursor at `5`. The cursor at `1` is deleted.
- `<left>` (`mc.prevCursor`): moves the main cursor to `3` and leaves a virtual cursor at`5` (the prior position). `<esc>` then moves the main cursor to `1`, which is enabled along with cursor at `5`. The cursor at `3` is deleted.
- `<right>` (`mc.nextCursor`): moves the main cursor to `1` and leaves a virtual cursor at `5` (the prior position). `<esc>` then moves the main cursor to `3`, which is enabled along with cursor at `5`. The cursor at `1` is deleted.
- `<down>` (`mc.lastCursor`): does not move the main cursor from `5` (it's considered the last cursor). `<esc>` then moves the main cursor to `3`, which is enabled along with the cursor at `1`. The original main cursor at `5` is deleted.

I could see how Scenario 1 is intentionally treating the main cursor like all the rest. But that seems to conflict with how the main cursor (now updated after a prev/next/first/last motion) is deleted once we `setCursorsEnabled(true)`, leaving only 2 cursors (1 main + 1 virtual) where navigation was previously presenting a worldview of 3 cursors (1 main + 2 virtuals).

### Resolution

To my mind, this contradiction could be resolved in one of two ways, depending on the direction you wanna fall.

1. Take the stance that the main cursor really is like all the virtual ones when we have `setCursorsEnabled(false)`.
    - The present `mc.enableCursors` action explicitly calls `ctx:mainCursor():delete()` [[ref]](https://github.com/jake-stewart/multicursor.nvim/blob/46dbc77c5b14ef79b707880a7c6ebf6d34c8398b/lua/multicursor-nvim/examples.lua#L279)
    - By removing that deletion, we would hold onto the main cursor instead of throwing it away
    - Thus, the main cursor wouldn't disappear after navigating to one of the virtual cursors by way of the `mc.{prev,next,first,last}Cursor` actions
2. Take the stance that the main cursor is actually separate from the virtual ones when we have `setCursorsEnabled(false)`.
    - Right now, `mc.{prev,next,first,last}Cursor` work by calling `Cursor:select()`, which mucks with `state.mainCursor`
    - This works sensibly under `setCursorsEnabled(true)`, but with `setCursorsEnabled(false)` it means `mc.enableCursors` is going to delete the cursor we just navigated to
    - So instead, you could use `ctx:mainCursor():setPos(cursor:getPos())` if cursors are disabled
    - Rather than point the `state.mainCursor` to a different object, this literally just moves the main cursor so that it overlaps one of the (separate) virtual cursors; `ctx:overlappedCursor()`'s return value would make sense here

Personally, I err towards the second one. To be clear, either is already achievable by using the low-level API:

```lua
function nextCursor()
  mc.action(function(ctx)
    local pos = ctx:mainCursor():getPos()
    local cursor = ctx:nextCursor(pos) or ctx:firstCursor()
    if ctx:cursorsEnabled() then
      cursor:select()
    else
      ctx:mainCursor():setPos(cursor:getPos())
    end
  end)
end

vim.keymap.set("n", "<right>", nextCursor)
```

Similarly, users are able to write their own implementation of `<c-q>` that avoids `mc.enabledCursors()` in favor of calling `ctx:setCursorsEnabled(true)` sans main cursor deletion.

Either way, I just thought it was worth pointing out as a potential point of friction in the stock behaviors of the high-level API.

**Comment by jake-stewart** [comment]
I will be making `getCursors()` not return the main cursor when cursors are disabled since we no longer consider it a cursor. this makes things like `nextCursor`, `firstCursor` more consistent.

Additionally, I will be making `matchCursors` and `splitCursors` no longer enable cursors. It will only split/match the main cursor, add more cursors, and remain in disabled mode.

**Comment by jake-stewart** [comment]
All done. Thanks for all the API feedback, it's very valuable.

**Comment by ajvondrak** [comment]
Awesome, the additional changes make sense to me on first glance. Glad I could help. 😄
