### ISSUE TITLE
proper jumplist support

### ISSUE THREAD

**Issue by ajvondrak** [jake-stewart/multicursor.nvim#25]
Would it make sense for `Cursor:setPos()` to push a position to the jump list as a rule? Or is that the wrong layer to do that? Would separate cursors need to maintain their own jump lists, or would the global jump list just pertain to the main cursor?

Context: in my mappings for prev/next/first/last cursor with `setCursorsEnabled(false)` (cf. #24), I manually added a `vim.cmd.normal({ "m'", bang = true })` before moving the main cursor. I haven't thought very far through the implications for the whole plugin, but it got me wondering about how the jump list gets along with multiple cursors in general and whether there was anything "smart" to do automatically. Might be a rabbit hole, I dunno. 😅

**Comment by jake-stewart** [comment]
It's completely by accident that the jumplist works at all for multiple cursors. I never put any effort into it and it just works (although I think there are oddities if you try to jump back multiple times). I should probably keep a separate jumplist per cursor to make sure it is consistent. Then yeah, setpos should push to the jumplist with an option not to.

**Comment by jake-stewart** [comment]
undolist is pretty shit to work with but we have `mc.jumpForward` and `mc.jumpBackward` which you can map to `<c-i>` and `<c-o>`. not perfect and doubt it can be.
