### ISSUE TITLE
Problem entering insert mode after split cursors

### ISSUE THREAD

**Issue by ErickKramer** [jake-stewart/multicursor.nvim#26]
Hi,
thank you for creating this plugin. I tried to recreate your example for the "Split" and I cannot get the insert to work.

I have the following

```python
def baz(x, y, z):
    pass
```

I do visual selection inside the parenthesis, do split on `,`, it then generates three cursors as shown in here 

![2024-09-25T08:41:09,399345837+02:00](https://github.com/user-attachments/assets/43e7898d-750d-4fc1-8835-dffa7c798b84)

Afterwards, I try pressing `i` or `a` and it does not work. `c` works, but it will then remove the letters under the cursor.

is there something that I am doing wrong or something missing in my configuration?

**Comment by jake-stewart** [comment]
Splitting the visual selection creates multiple visual selections. Try pressing `<esc>`. Let me know if this does not fix your issue.

**Comment by ErickKramer** [comment]
> Splitting the visual selection creates multiple visual selections. Try pressing `<esc>`. Let me know if this does not fix your issue.

Thanks for the explanation. That did the trick. I did not realize that it kept me in visual mode after the split.
