### ISSUE TITLE
cursor mode change events

### ISSUE THREAD

**Issue by aidancz** [jake-stewart/multicursor.nvim#28]
Thank you for your awesome plugin <3

With this autocmd:

```
autocmd InsertLeave * :normal `^
```

the cursor stay still when leaving insert mode

how can i make the added cursors behave the same as the main cursor?

**Comment by jake-stewart** [comment]
Currently not possible. Shouldn't be too hard to add.

**Comment by jake-stewart** [comment]
Good to go. Try `:Lazy update` and add this to your config:

```lua
mc.onModeChanged(function(cursor, oldMode, newMode)
    if oldMode == "i" and newMode == "n" then
        cursor:feedkeys("`^")
    end
end)
```
