### ISSUE TITLE
Up and Down cursor adding to ignore certain lines?

### ISSUE THREAD

**Issue by unphased** [jake-stewart/multicursor.nvim#29]
I think this is the main thing preventing the `<Up>` and `<Down>` suggested binds from being really practical, which is that extra cursors are made and dropped at the empty lines in the middle. Often we have code with empty lines to group things neatly, take the suggested config for this plugin for example: 

```lua
      -- Add cursors above/below the main cursor.
      vim.keymap.set({"n", "v"}, "<s-up>", function() mc.addCursor("k") end)
      vim.keymap.set({"n", "v"}, "<s-down>", function() mc.addCursor("j") end)

      -- Add a cursor and jump to the next word under cursor.
      vim.keymap.set({"n", "v"}, "<c-d>", function() mc.addCursor("*") end)

      -- Jump to the next word under cursor but do not add a cursor.
      vim.keymap.set({"n", "v"}, "<c-e>", function() mc.skipCursor("*") end)

      -- Rotate the main cursor.
      vim.keymap.set({"n", "v"}, "<s-left>", mc.nextCursor)
      vim.keymap.set({"n", "v"}, "<s-right>", mc.prevCursor)
```

Suppose I want to use multicursor to do some alignment of commas across all these lines, it would be natural to use a direct way like adding a cursor on `j`, but not only would we want to somehow skip the empty lines, we'd also want to skip the comment lines!

It's unclear if this can be done with sane code, but i would definitely think it not too arduous to have such logic:

- if initial cursor (prior to entering multicursor mode) was on actual code, then when adding a cursor in `j` or `k` direction:
   - skip adding cursor if we're on an empty line or if the length of the line is short and would cause the cursor to get yanked left
   - skip adding cursor if we land on a comment

I'd be partial to using treesitter to query the semantics of the code but I believe there are ways to do that even without treesitter. Here's how I did it in pre-treesitter world:

```vim
function! SmartInsertStartOfLine()
	if synIDattr(synID(line("."), col("."), 1), "name") =~ "Comment"
		normal! ^w
		startinsert
	else
		" why do i need to use feedkeys? who knows?
		call feedkeys('I', 'n')
	endif
endfun
" http://stackoverflow.com/a/22282505/340947
nnoremap I :call SmartInsertStartOfLine()<CR>
```

I am pretty sure even when we use treesitter, the native vim syntax parsing still goes on under the hood, so checking for comment this way ought to be fairly robust and should skirt around depending on treesitter?

For now, we have to rely on `addCursor("*")` on a suitable choice (such as `set` in this example) to get cursors made on the code lines.

**Comment by jake-stewart** [comment]
This is certainly possible with the CursorAPI. I will write an example when I have time. For now, try disabling cursors, skipping past the junk lines, then adding lines below like usual.

**Comment by jake-stewart** [comment]
i have added new examples `mc.lineAddCursor()` and `mc.lineSkipCursor()` which both take `-1` or `1` for direction. it is included in readme.

it skips lines which are too short. if you want to skip a comment, then when your cursor is on the comment, use the `mc.lineSkipCursor(1)` and it will jump down a line without leaving a cursor.
