### ISSUE TITLE
How to add cursor under current cursor?

### ISSUE THREAD

**Issue by ShiChenCong** [jake-stewart/multicursor.nvim#3]
Thank you for the useful plugin. 
How to add curosr under current curosr? I can't find the way in the doc.

**Comment by jake-stewart** [comment]
```
    -- add cursors above/below the main cursor
    vim.keymap.set({"n", "v"}, "<up>", function() mc.addCursor("k") end)
    vim.keymap.set({"n", "v"}, "<down>", function() mc.addCursor("j") end)
```

with the default config you can press `<up>` or `<down>` to add a cursor above or below the current cursor.

**Comment by ShiChenCong** [comment]
can use it without motion？just under current cursor
