### ISSUE TITLE
Removes indentation in .norg files

### ISSUE THREAD

**Issue by Rahmyeon** [jake-stewart/multicursor.nvim#30]
# When using multiple cursors in .norg files. Indentation is removed.

## Steps to replicate:
1. Open any random .norg file
2.  Create new cursors (mouse or keyboard does not seem to affect this bug)
3. Insert text
4. Press escape
5. Loose Indentation

https://github.com/user-attachments/assets/7241d7e8-bd02-40fb-8897-cc683a5be297

**Comment by Rahmyeon** [comment]
Though the plugin is amazing thanks for all your work.

**Comment by jake-stewart** [comment]
What plugins are you using for .norg files? Can you post min reproducible example? Thanks

**Comment by Rahmyeon** [comment]
.norg, I only use Neorg for .norg files and that's it. I am doing this on windows 11 laptop with windows Terminal.
# Min reproducible steps:
1. create a .norg file (The Neorg plugin is required to reproduce the bug)
2. add cursors to lines of your choice in normal mode.
3. insert text
4. press escape after the text inserted
5. Each lines indentation should be automatically removed after escape is pressed.


https://github.com/user-attachments/assets/11262693-7aca-464b-8522-9cfb65c21370

**Comment by jake-stewart** [comment]
@Rahmyeon Even when multicursor.nvim is not installed, Neorg removes indentation when inserting. This is not a multicursor.nvim bug. I think you should open an issue for Neorg if this is undesired behaviour. I have no clue what norg is so I can't give much more input.

**Comment by Rahmyeon** [comment]
K, thanks I will report vhyrro.
