### ISSUE TITLE
add improved match cursor word example

### ISSUE THREAD

**Issue by RAV64** [jake-stewart/multicursor.nvim#32]
In this example file
```
v1 = "",
v2 = "", -- Comment 
v3 = "", -- Comment
```

Using this keybinding

``` lua
set({ "n" }, "<c-n>", function()
  mc.addCursor("*")
end)
```

Trying to add a cursor fails in these places

Cursor on:
- Line 1:
   - ,
- Line 2:
  - =
  - "
  - ,
  - \-
- Line 3:
  - =
  - "
  - ,
  - \-
- On any space character

Additionally the keybind causes an error message when used on an empty line
```
E348: No string under cursor
E5108: Error executing lua: ...nvim/lazy/multicursor.nvim/lua/multicursor-nvim/core.lua:30: An action is already being p
erformed
stack traceback:
        [C]: in function 'error'
        ...nvim/lazy/multicursor.nvim/lua/multicursor-nvim/core.lua:30: in function 'action'
        .../lazy/multicursor.nvim/lua/multicursor-nvim/examples.lua:262: in function 'clearCursors'
        /Users/xxx/.config/nvim/lua/plugin/multicursor.lua:32: in function </Users/xxx/.config/nvim/lu
a/plugin/multicursor.lua:30>
        [C]: in function 'feedkeys'
        ...multicursor.nvim/lua/multicursor-nvim/cursor-manager.lua:25: in function <...multicursor.nvim/lua/multicursor
-nvim/cursor-manager.lua:20>
        [C]: in function 'pcall'
        ...multicursor.nvim/lua/multicursor-nvim/cursor-manager.lua:1080: in function 'feedkeys'
        .../lazy/multicursor.nvim/lua/multicursor-nvim/examples.lua:194: in function 'callback'
        ...multicursor.nvim/lua/multicursor-nvim/cursor-manager.lua:1322: in function 'action'
        ...nvim/lazy/multicursor.nvim/lua/multicursor-nvim/core.lua:34: in function <...nvim/lazy/multicursor.nvim/lua/m
ulticursor-nvim/core.lua:33>
        [C]: in function 'pcall'
        .../multicursor.nvim/lua/multicursor-nvim/input-manager.lua:58: in function 'performAction'
        ...nvim/lazy/multicursor.nvim/lua/multicursor-nvim/core.lua:33: in function 'action'
        .../lazy/multicursor.nvim/lua/multicursor-nvim/examples.lua:181: in function 'addCursor'
        .../lazy/multicursor.nvim/lua/multicursor-nvim/examples.lua:228: in function 'addCursor'
        /Users/xxx/.config/nvim/lua/plugin/multicursor.lua:15: in function </Users/xxx/.config/nvim/lu
a/plugin/multicursor.lua:14>
```

**Comment by jake-stewart** [comment]
That is how the binding for `*` behaves. Try the same motions without the plugin enabled.

You will find that using `*` in visual mode works better for selecting punctuation:

```lua
set({ "n", "v" }, "<c-n>", function()
  mc.addCursor("*")
end)
```

As for the error, that's again how the `*` motion behaves. `addCursor` simply adds a cursor and then moves the main cursor using the provided motion.

Perhaps a new example function should be created which behaves differently.

**Comment by RAV64** [comment]
I'm not certain how to test the `*` motion without the plugin.

The behavior might be correct in that case, but it doesn't really match my mental model for what I expect to happen when issuing this keybinding (Might be skill issue on my part ;) ). If it's working as Intended I believe another example function which would work as expected in this example file would be great.

(Jumping backwards would also be appreciated :) )

**Comment by jake-stewart** [comment]
I mean, disable the plugin and then press `*`. It will jump to the next word under the cursor. That is what `*` does with or without the plugin. Try using `*` without the plugin and `addCursor("*")` with the plugin and you should see the same behaviour. If you want to search for special chars, then visually select the chars first before pressing `*`, just like you would without the plugin.

**Comment by RAV64** [comment]
> I mean, disable the plugin and then press `*`. It will jump to the next word under the cursor. That is what `*` does with or without the plugin. Try using `*` without the plugin and `addCursor("*")` with the plugin and you should see the same behaviour. If you want to search for special chars, then visually select the chars first before pressing `*`, just like you would without the plugin.

Oh neat - Sorry for my ignorance -  I wasn't aware of `*` functionality - that makes sense, thanks 👍🏻 It does indeed behave the same.

Expected behavior - This issue can be closed. Thanks!

**Comment by jake-stewart** [comment]
i still think this issue can remain open. the default behaviour of `*` doesn't make much sense when extending cursors. when i have time i'll try make a better example.

**Comment by jake-stewart** [comment]
i've added new examples `mc.matchAddCursor` and `mc.matchSkipCursor`. they are in the readme.

1. matches visual selection if in visual mode.
2. matches word under cursor if there is one.
3. matches character under cursor if there is one.
4. matches empty lines

can specify direction with `-1` or `1`
