### ISSUE TITLE
[Discussion] Tentative steps reproducing the video showcase

### ISSUE THREAD

**Issue by franckrasolo** [jake-stewart/multicursor.nvim#38]
Hi @jake-stewart!

While integrating the plugin to my Neovim config using default keymaps, I've attempted to reproduce the refactoring showcased in this repo's `README` video using the steps broken down below:

1. type `0gg` to position the cursor on the `f` of the first function, in normal mode
2. repeat `<c-n>` to create a cursor for each function
3. type `i` to prepend `declare ` followed by `<esc>`
4. type `4w` to position cursors on the first function parameter
5. type `vt)` to select all function parameters
6. type `S` followed by `, ` to split visual selections
7. type `<c-c>` to exit visual mode
8. type `a` followed by `: number` then `<esc>`
9. type `$` to converge cursors with the end of each line
10. type `h` to move cursors to just before the last `)` and insert `: number` followed by `<esc>`
11. type `lc};<esc>` to replace each code block with a semicolon
12. type `04wvt)S` followed by `, ` to create cursors for each parameter
13. type `3b<c-c>i<cr><esc><leader>x/)<cr>i<cr><esc>` to place each parameter on a new line
14. type `0gg/, <cr>` and repeat `<c-n>` to select commas, followed by `lx<esc>` to remove trailing spaces

Would you mind reviewing or even suggesting more optimal steps?

I'm considering recording a quick video with these steps overlayed somehow as it may help other folks understand what's going on.

Thanks for this amazing plugin!

**Comment by jake-stewart** [comment]
Looks good. Two ways I spotted that you could be more efficient:

1. instead of typing `4w` and then `vt(`, just type `vi(` from the start of the line. It will automatically jump to the opening paren and select inside of it.
2. instead of typing `a: number` twice, just press `.` the second time.

I never bothered to remove the trailing whitespace in the example, but one way you could do it is:

1. type `vi(` to select inside of the parens.
2. type `M<space>` to select each space.
3. type `x` to delete each space.
4. type `vi(` to select within the parens again. The cursors will merge into one cursor.
5. Continue as normal, typing `S,<space>` to split to each param.

In the near future I plan on adding temporary multiple cursors which would make this even easier, but it's hard to explain it with words. I will put a video demo in the readme when it's done if it turns out as envisioned.

Thanks and I'm glad you enjoy the plugin.

**Comment by franckrasolo** [comment]
> 3 ways I spotted that you could be more efficient:
> 1. instead of typing 4w and then vt), just type vi( from the start of the line. It will automatically jump to the opening paren and select inside of it.
> 2. instead of typing a: number twice, just press . the second time.
> 3. i'm not sure how you deleted the function body, but for this I press d% while on the opening brace {. It deletes all the contents.

1. `vi(` doesn't work for me, possibly due to one of the text-objects plugins...
2. good shout, thanks!
3. I used `c};`, but `c%;` works equally well.

**Comment by franckrasolo** [comment]
I can confirm that `vi(` now works after I disabled [chrisgrieser/nvim-various-textobjs](https://github.com/chrisgrieser/nvim-various-textobjs).

**Comment by jake-stewart** [comment]
@franckrasolo This is what I meant by temporary multiple cursors. I can clone all cursors, disabling the original ones, and use the new cursors to delete the whitespace. Once I'm done, I can delete these new cursors and my original cursors are enabled.

https://github.com/user-attachments/assets/1879bc7c-5d1c-4db0-a4f3-744e2a9a6532

**Comment by franckrasolo** [comment]
Nice! I'm curious to try them out...

**Comment by jake-stewart** [comment]
@franckrasolo i added them yesterday. it's `mc.duplicateCursors()` which is in the readme

**Comment by franckrasolo** [comment]
@jake-stewart I've managed to significantly reduce the number of steps:

1. from the `f` of the first function, repeat `<c-n>` to create cursors
2. type `/)a: number<esc>` to append each function's return type
3. type `lc%;<esc>` to replace each code block with a semicolon
4. type `Ideclare <esc>` to prepend the `declare` keyword
5. type `vt)/` followed by `, <cr>` to split function parameters
6. type `<c-c>a: number<esc>` to append parameter types
7. type `3bi<cr><esc>` to place each parameter on a separate line
8. type `<leader><c-q>v$M` followed by `, <cr>` and `lD<esc>` to remove trailing spaces – with duplicate cursors! 🥳
9. type `/)i<cr><esc>` to place each function's return type on a new line

_**ps:** `vi(` stopped working on other cursors for some reason, hence the above steps_

**Comment by jake-stewart** [comment]
Very cool. I notice in step 2 you did `/)` instead of `f)`?
I like that you removed the need to have to split twice.
I also love the duplicated cursors. I wonder how useful they will end up being

**Comment by franckrasolo** [comment]
> Very cool. I notice in step 2 you did /) instead of f)?

Just like with `vi(`, none of the `f`, `t`, `F`, `T` motions behave as expected on other cursors.

**Comment by jake-stewart** [comment]
strange. they all work for me. could open an issue if it still doesnt work with other plugins disabled.

**Comment by franckrasolo** [comment]
Everything works as expected now with the above commits. For posterity, I'll summarise my findings as follows:

1. the `mini.ai` plugin is what changed the behaviour of `vi(`
2. the `flit.nvim` plugin is what restored the behaviour of `f/t/F/T` motions

**Comment by jake-stewart** [comment]
damn plugins. glad you got it sorted
