### ISSUE TITLE
Compatibility with ts Autotag

### ISSUE THREAD

**Issue by Rahmyeon** [jake-stewart/multicursor.nvim#39]
# Issues with nvim-ts-auto-tag
Hello, again. I am sorry to disturb you again but when I try to use ts-auto-tag
in combination with your amazing plugin, it only completes the line the
primary cursors are on.

### This happens on Windows, using Windows terminal
1. add cursors to the line of your choice in a file that is compatible with ts-auto-tag

2.  try to type multiple similar opening and closing elements (New to programming and don't know the proper terminology)

3.  Press escape

Should show incomplete text: example video below.
also please ignore the a's before the code example, it was just lazy way
of me getting stuff on multiple different lines.

https://github.com/user-attachments/assets/2d6811d5-de1a-4dce-bffc-d25e9ee1e050

- ps. thanks, I have opened two issues in under two weeks. I don't mean to disturb.
-  It may just be a compatibility thing and I am whining.

have a great day/week/month/year !

**Comment by jake-stewart** [comment]
hi, open as many issues as youd like.

sadly this again is not a multicursor.nvim bug, it is a [nvim-ts-autotag bug](https://github.com/windwp/nvim-ts-autotag/issues/166). Their motion is not dot repeatable, so there is no way for multicursor.nvim to know what to repeat.

**Comment by Rahmyeon** [comment]
Thanks to you, I have just realized that Autotag has a Windows-specific bug.
I appreciate your help.
