### ISSUE TITLE
When starting visual mode, cursors move different amounts

### ISSUE THREAD

**Issue by mikavilpas** [jake-stewart/multicursor.nvim#4]
With two cursors, it looks like `vl` (start visual mode and move to the right once) moves one cursor once and the second twice:

https://github.com/user-attachments/assets/a0a70e51-1068-4035-8af5-27021042f658

**Comment by jake-stewart** [comment]
sadly i cannot replicate.

1. have you tried `:Lazy update`
2. have you tried without plugins?
3. have you tried with clean config?
4. neovim version?

thanks

**Comment by mikavilpas** [comment]
I can replicate the issue with lazyvim's reproduction template using the following

```lua
-- repro.lua
vim.env.LAZY_STDPATH = ".repro"
load(
  vim.fn.system(
    "curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"
  )
)()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    {
      "jake-stewart/multicursor.nvim",
      config = function()
        local mc = require("multicursor-nvim")

        mc.setup()

        vim.keymap.set({ "n", "v" }, "<c-n>", function()
          mc.addCursor("*")
        end)
      end,
    },
  },
})
```


https://github.com/user-attachments/assets/3cccb537-ffc5-4e7c-bfb7-e60e73631380

I cannot reproduce it without lazyvim though.

```
NVIM v0.11.0-dev-681+g5f95f1249
Build type: Release
LuaJIT 2.1.1724512491
Run "nvim -V1 -v" for more info
```

**Comment by mikavilpas** [comment]
I was able to narrow it  down to the conflicting plugin with a manual binary search. It seems to be fixed when I disable which-key in the reproduction setup.

So this fixes the bug:

```lua
---@module "lazyvim"

vim.env.LAZY_STDPATH = ".repro"
load(
  vim.fn.system(
    "curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"
  )
)()

require("lazy.minit").repro({
  ---@type LazySpec
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { "folke/which-key.nvim", enabled = false },  -- 👈🏻 disabling this plugin with enabled=false makes the bug not occur
    {
      "jake-stewart/multicursor.nvim",
      config = function()
        local mc = require("multicursor-nvim")

        mc.setup()

        vim.keymap.set({ "n", "v" }, "<c-n>", function()
          mc.addCursor("*")
        end)
      end,
    },
  },
})
```

**Comment by jake-stewart** [comment]
thanks for the help.

when i get time today or tomorrow i'll try get the plugin to work with which-key

**Comment by jake-stewart** [comment]
@mikavilpas latest commit should make it work with which-key

turned out which-key caused a lot more errors than just the one you found. it seems to use feedkeys for the pressed key, which means vim.on_key triggers twice (and thus the cursor moved twice). i now wrap feedkeys and keep track of the keys fed, and ignore them. it is a hack but it seems to work well.

let me know if you see any problems, thanks.

**Comment by mikavilpas** [comment]
Thanks, that solves the issue!
