### ISSUE TITLE
support overlapped mappings

### ISSUE THREAD

**Issue by dmtrKovalenko** [jake-stewart/multicursor.nvim#41]
Pretty much visible on the video

https://github.com/user-attachments/assets/dd981f03-df9d-4290-b736-628255e9e3a5

might be an issue with my configuration, it is based on the example here it is:

https://github.com/dmtrKovalenko/my-nvim-config/blob/895d4c46eda51cc946cdb2958a673ad654499fd8/lua/multicursor-lazy.lua#L3-L99

would appreciate any hint

**Comment by jake-stewart** [comment]
init.lua line 573 you map a key to `lv`:

```lua
["lv"]·=·"@assignment.lhs",
```

As a result, when you press `l`, we have to wait to see whether you meant `l` or are about to press `v` for `lv`. I don't like keys sharing bindings for this reason.

Remove/change the `lv` keymap in your config.

Thanks

**Comment by jake-stewart** [comment]
sorry this is definitely a bug. after the second `l`, it should have figured out what the first `l` was for.

not sure if this can be fixed though. while pressing `l`, your nvim is never in a safe state, and so the keys are not applied until you press a different key.

i will investigate this more when i have time. for now, you can either be happy with the lack of feedback (looks like everything still works), or remap the key.

**Comment by jake-stewart** [comment]
can possibly wrap `vim.keymap.set`

**Comment by dmtrKovalenko** [comment]
Thank you for your investigation, remapping lv is a feasible workaround, which is fine

**Comment by jake-stewart** [comment]
i just tried [an autopairs plugin](https://github.com/jiangmiao/auto-pairs) and it successfully sets the `.` register for us, so it works for multicursor. hooray !!

**Comment by jake-stewart** [comment]
i have tried a few ideas but i think this is a wontfix. there are a lot of edge cases if i try to handle input while nvim is not in a safe state. thanks for opening the issue, though.
