### ISSUE TITLE
Wrong edits are applied if the cursors are on the same line

### ISSUE THREAD

**Issue by archilkarchava** [jake-stewart/multicursor.nvim#45]
Regression in the most recent commit https://github.com/jake-stewart/multicursor.nvim/commit/6cc16c39a45f5e8c789e3c7e6adb4ba6fc164403

### Demo
https://github.com/user-attachments/assets/b6da84ea-ee66-4594-8d2c-c4a43d661fba

**Comment by jake-stewart** [comment]
fixed. im very sorry
