### ISSUE TITLE
[Help] Add cursor to all matches of the word under the cursor?

### ISSUE THREAD

**Issue by Ajaymamtora** [jake-stewart/multicursor.nvim#47]
One thing I couldn't figure out how to do after migrating from https://github.com/brenton-leighton/multiple-cursors.nvim (MultipleCursorsAddMatches) -- is how to add a cursor at all matches of a word. 

Could this be implemented please, or is there a way to configure it?

For instance if I invoked it on the f on function, it should add cursors to each word that matched function

![image](https://github.com/user-attachments/assets/1120b5eb-a582-4b26-94bc-dba75e7c2c94)

![image](https://github.com/user-attachments/assets/fe544d7e-faea-4dee-9fbb-d09053a8d3d0)

**Comment by jake-stewart** [comment]
I will write another example when I have time.
