### ISSUE TITLE
Feature: Add the ability to see all cursors typing at the same time

### ISSUE THREAD

**Issue by Rahmyeon** [jake-stewart/multicursor.nvim#49]
# Add the ability to turn on seeing all cursors type simultaneously.
The reason why I suggest this feature is because sometimes cursors interfere with other text and it allows people to catch their mistakes
faster as sometimes the cursor your looking at is correct but the others are not. 

Thanks

**Comment by jake-stewart** [comment]
that would require simulating vim which would lead to inconsistencies. sadly this is a wontfix.

**Comment by jake-stewart** [comment]
> Check out https://github.com/mg979/vim-visual-multi

vim visual multi simulates insert mode which leads to many inconsistencies,
affecting insert mappings, undo/redo, autocompletion, snippets, and lots more.

**Comment by jensenr30** [comment]
> > Check out https://github.com/mg979/vim-visual-multi
> 
> vim visual multi simulates insert mode which leads to many inconsistencies, affecting insert mappings, undo/redo, autocompletion, snippets, and lots more.

Actually, after using vim-visual-multi for a bit, I've switched back to your plugin.  It seems to be more user friendly out of the box.
