### ISSUE TITLE
bug: aligning cursors on an empty line leaves one space out the first time

### ISSUE THREAD

**Issue by mikavilpas** [jake-stewart/multicursor.nvim#5]
When I have an empty line as well as a line with text, `alignCursors` is able to align the cursors by adding spaces. But one space is left out the first time I do it (it's fixed the second time I do it)

https://github.com/user-attachments/assets/be6ed214-778c-40df-9061-49409e1cbfcb

Here I add two cursors and call `alignCursors` twice.

**Comment by jake-stewart** [comment]
latest commit implements this as `mc.visualToCursors()`

it works for multiple visual selections.

let me know if you like how it works.
