### ISSUE TITLE
viw doesn't work as expected

### ISSUE THREAD

**Issue by alex35mil** [jake-stewart/multicursor.nvim#54]
Maybe I misunderstood how plugin works, but here is the case I bumped into.

Text:

```
modules/hrms.dtsi
modules/combos.dtsi
modules/macros.dtsi
modules/behaviors.dtsi
modules/mouse.dtsi
```

Initial state:

![CleanShot 2024-10-07 at 12 10 17@2x](https://github.com/user-attachments/assets/a79c62dc-2392-4f06-8c0f-22ef6a195d87)

Added cursors:

![CleanShot 2024-10-07 at 12 10 25@2x](https://github.com/user-attachments/assets/68204756-a154-40b7-b77f-19912fc5707d)

`ww`:

![CleanShot 2024-10-07 at 12 10 32@2x](https://github.com/user-attachments/assets/1c12c23e-db62-4b18-82df-0c2327341bfd)

`viw`:

Expected - `hrms`, `combos`, `macros`, `behaviors`, and `mouse` are selected.
Actual:
![CleanShot 2024-10-07 at 12 10 44@2x](https://github.com/user-attachments/assets/c6569fde-4dae-4c50-b782-88f06cc0a5ae)

**Comment by jake-stewart** [comment]
works for me. have you tried without plugins and after doing `:Lazy update` ?

**Comment by alex35mil** [comment]
Checked with minimal LazyVim setup - still the same issue:

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
        {
            "LazyVim/LazyVim",
            import = "lazyvim.plugins",
        },
        {
            "jake-stewart/multicursor.nvim",
            branch = "1.0",
            keys = {
                {
                    "<C-Up>",
                    function()
                        require("multicursor-nvim").lineAddCursor(-1)
                    end,
                    mode = { "n", "v" },
                },
                {
                    "<C-Down>",
                    function()
                        require("multicursor-nvim").lineAddCursor(1)
                    end,
                    mode = { "n", "v" },
                },
            },
            config = function()
                require("multicursor-nvim").setup()
            end,
        },
    },
})
```

**Comment by jake-stewart** [comment]
thanks. looks like it's caused by mini.ai. i will investigate to see it we can work alongside it

**Comment by alex35mil** [comment]
Works, thank you!
