### ISSUE TITLE
[Question] Add cursor to next/prev match of visual selection

### ISSUE THREAD

**Issue by Ajaymamtora** [jake-stewart/multicursor.nvim#56]
Is there a way to add a cursor to the next instance of the visually selected text?

For example when adding a cursor in this scenario, add a cursor to the next `ction` ?

<img width="370" alt="Screenshot 2024-10-08 at 18 35 26" src="https://github.com/user-attachments/assets/fc349f70-f0a1-4535-a4bb-42990ff7167d">

**Comment by jake-stewart** [comment]
yeah just map to matchAddCursor in visual mode

**Comment by jake-stewart** [comment]
let me know if it doesn't work for you
