### ISSUE TITLE
High CPU usage and terminal hang when switching apps with multicursor enabled in Neovim (LazyVim)

### ISSUE THREAD

**Issue by theerapat-pkcn** [jake-stewart/multicursor.nvim#57]
This plugin is excellent, but I've encountered an issue that I’m unsure if others are experiencing as well.

When the multicursor feature is enabled (using `mc.addCursor`), if I switch to another application (such as a web browser) from the terminal, the terminal with Neovim running becomes unresponsive and CPU usage spikes to 99%. To resolve this, I have to close the terminal and restart Neovim.

As a temporary workaround, I’ve started using `mc.clearCursors` before switching applications to prevent the issue.

My current setup is LazyVim on Fedora 40, but I have also experienced the same issue on Macbook Pro 2016 with Alacritty, using the same LazyVim configuration.

Here are my configs.

```return {
  "jake-stewart/multicursor.nvim",
  branch = "1.0",
  config = function()
    local mc = require("multicursor-nvim")

    mc.setup()

    -- Add cursor at current position.
    vim.keymap.set({ "n", "v" }, "<c-o>", function()
      mc.addCursor("j")
      mc.deleteCursor()
      mc.disableCursors()
    end)

    -- Add and remove cursors with control + left click.
    vim.keymap.set("n", "<c-leftmouse>", mc.handleMouse)

    -- Go to the first cursor and enable all cursors.
    vim.keymap.set({ "n", "v" }, "<c-i>", function()
      mc.firstCursor()
      mc.enableCursors()
    end)

    -- Use <c-q> to clear all cursors.
    vim.keymap.set({ "n", "v" }, "<c-q>", function() mc.clearCursors() end)

    -- Exit multicursor mode and go to normal mode.
    vim.keymap.set({ "n", "v" }, "<c-u>", function()
      if mc.cursorsEnabled() then
        -- Stop other cursors from moving.
        -- This allows you to reposition the main cursor.
        mc.disableCursors()
      else
        mc.addCursor()
      end
    end)

    -- Add a cursor and jump to the next word under cursor.
    -- Like <c-d> in VSCode.
    vim.keymap.set({ "n", "v" }, "<c-n>", function() mc.addCursor("*") end)

    -- Jump to the next word under cursor but do not add a cursor.
    vim.keymap.set({ "n", "v" }, "<c-m>", function() mc.skipCursor("*") end)

    -- Delete the nearest cursor.
    vim.keymap.set({ "n", "v" }, "<leader>x", mc.deleteCursor)

    -- Customize how cursors look.
    vim.api.nvim_set_hl(0, "MultiCursorCursor", { link = "Cursor" })
    vim.api.nvim_set_hl(0, "MultiCursorVisual", { link = "Visual" })
    vim.api.nvim_set_hl(0, "MultiCursorDisabledCursor", { link = "Visual" })
    vim.api.nvim_set_hl(0, "MultiCursorDisabledVisual", { link = "Visual" })
  end,
}

**Comment by jake-stewart** [comment]
does disabling `noice.nvim` fix it?

```lua
    { "noice.nvim", enabled = true },
```

for some reason with this plugin installed (with or without multicursor), safe state executes non stop. put this line in your config to see what i mean.

```lua
local i = 0
vim.api.nvim_create_autocmd("SafeState", {
    pattern = "*", callback = function()
        i = i + 1
        vim.print("SafeState " .. i)
    end
})
```

**Comment by jake-stewart** [comment]
if `noice.nvim` isn't the cause then i'm unable to replicate it. try disabling your plugins to see if it fixes it. if fixed, try find which one.

**Comment by theerapat-pkcn** [comment]
I tried disabling various plugins to identify the source of the problem, and it turns out that it’s not related to the default plugins used by LazyVim. The issue was caused by a scroll bar plugin I added later, called `lewis6991/satellite.nvim`. After disabling it, everything works fine.

Thank you for your help, and thanks again for creating such a wonderful plugin.

**Comment by jake-stewart** [comment]
thanks, glad you got it sorted.

when i get time, i will investigate `satellite.nvim` to see if i can make them play nice. i'll let you know.

**Comment by jake-stewart** [comment]
@theerapat-pkcn you can now use `satellite.nvim` with multicursor. let me know if any more problems.

`satellite.nvim` entered an infinite loop because it kept reading for input but the multicursors generate input. i just made it so polling for input always says there is no more input when multiple cursors. seems to work

**Comment by theerapat-pkcn** [comment]
It’s working now! Thank you so much for your hard work. I really appreciate it. :)
