### ISSUE TITLE
writing dot in insert mode, get things duplicated

### ISSUE THREAD

**Issue by bassamsdata** [jake-stewart/multicursor.nvim#58]
Hello,

I'm encountering an issue with multiple cursors. When I add multiple cursors, enter insert mode, and type something followed by a dot (`.`), everything before the dot is duplicated after the cursor when I return to normal mode in the main cursor.

**Steps to reproduce:**
1. Add multiple cursors.
2. Enter insert mode.
3. Type some text, then type a dot (`.`).
4. Return to normal mode.
5. The issue appears on the main cursor line.

![Kapture 2024-10-12 at 12 06 39](https://github.com/user-attachments/assets/9bf9558b-17c0-4274-869a-2f0845ecae68)

Thanks so much for this amazing plugin!

Here’s my config:

```lua
return {
  {
    "jake-stewart/multicursor.nvim",
    lazy = true,
    -- commit = "d090b6f",
    keys = { "<c-n>", "<c-p>", "<up>", "<down>" },
    config = function()
      local mc = require("multicursor-nvim")

      mc.setup()

      -- use MultiCursorCursor and MultiCursorVisual to customize
      -- additional cursors appearance
      vim.api.nvim_set_hl(0, "MultiCursorCursor", { link = "TermCursor" })
      vim.api.nvim_set_hl(
        0,
        "MultiCursorVisual",
        { link = "DiagnosticVirtualTextOk" }
      )

      vim.keymap.set("n", "<esc>", function()
        if mc.hasCursors() then
          mc.firstCursor()
          mc.clearCursors()
          vim.cmd.noh()
        else
          vim.cmd.noh()
        end
      end)

      ---@param key string
      ---@param action fun()
      local function checkCursor(key, action)
        return function()
          if mc.hasCursors() then
            action()
          else
            vim.cmd.norm(key)
          end
        end
      end

      -- stylua: ignore start 
      vim.keymap.set("v", "S", checkCursor("S", mc.splitCursors))
      vim.keymap.set( { "n", "v" }, "<left>", checkCursor("<left>", mc.nextCursor))
      vim.keymap.set( { "n", "v" }, "<right>", checkCursor("<right>", mc.prevCursor))
      -- add cursors above/below the main cursor
      vim.keymap.set({ "n","v" },  "<up>",   function() mc.addCursor("k") end)
      vim.keymap.set({ "n","v" },  "<down>", function() mc.addCursor("j") end)
      -- add a cursor and jump to the next word under cursor
      vim.keymap.set({ "n","v" },  "<c-n>",  function() mc.addCursor("*") end)
      -- jump to the next word under cursor but do not add a cursor
      vim.keymap.set({ "n","v" },  "<c-s>",  function() mc.skipCursor("*") end)
      -- rotate the main cursor
      -- delete the main cursor
      vim.keymap.set({"n", "v"},     "<leader>x", mc.deleteCursor)
      -- add and remove cursors with control + left click
      vim.keymap.set("n",  "<c-leftmouse>", mc.handleMouse)
      -- stylua: ignore end
    end,
  },
}
```

**Comment by bassamsdata** [comment]
Alright, I tested it with a minimal config, and the issue didn’t occur. However, when I tested with a fresh LazyVim install, the issue did appear. It seems there’s a conflict with a specific plugin in both my config and LazyVim. I’ll look into it further. I also saw issue #44, but I’m not sure if it’s related.

thank you

**Comment by jake-stewart** [comment]
@bassamsdata for some reason lazy maps `.` to `.<C-G>u` in insert mode which messes with undo. for now you can unmap `.`

i will try to make `<C-g>u` work with multicursor

**Comment by jake-stewart** [comment]
fixed. try `:Lazy update` and let me know if any problems.

if you use `<C-G>u` three times (by pressing `.` three times in insert mode), then you need to press `u` three times to undo the insertion. virtual cursors are not aware of this and will not undo in parts like the main cursor does. it's not a big deal since you can press `u` three times and then the cursors are in sync.

probably i dont make much sense explaining that but whatever it works good

**Comment by bassamsdata** [comment]
Thank you so much for the quick fix, it works perfectly!

> for some reason lazy maps . to .<C-G>u in insert mode which messes with undo. for now you can unmap .

Yeah, I have this too. It’s helpful because pressing `.` adds to the undo history, allowing me to undo in smaller increments, which is especially useful when programming in OOP languages like Python.

> probably i dont make much sense explaining that but whatever it works good

I completely understood your explanation, and that’s totally fine! Pressing multiple `u`s is no problem at all. Thanks again!
