### ISSUE TITLE
`matchCursors` fails if there's empty line in selection

### ISSUE THREAD

**Issue by tmarkov** [jake-stewart/multicursor.nvim#59]
If I select in visual mode some text, and there's an empty line in there, and then I use `matchCursors`, I get an error:

`Vim:E964: Invalid column number: 0`

Then, instead of getting cursors at each match, I get a bunch of cursors: one at each match before the empty line (as expected), but also no cursor at matches after the empty line, and a cursor at the end of every line (both before and after the empty line).

**Comment by jake-stewart** [comment]
fixed. try `:Lazy update` and let me know if any problems. thanks for opening the issue.
