### ISSUE TITLE
feature: add cursors for each visually selected line

### ISSUE THREAD

**Issue by mikavilpas** [jake-stewart/multicursor.nvim#6]
Hi! I love the idea with this plugin - it's quite powerful. I implemented the following feature and would like to suggest also implementing it in the plugin so others could benefit from it:

https://github.com/user-attachments/assets/f46bfdad-df4d-4800-9e33-fdcd53c85c57

It can also be used for visual block selections:

https://github.com/user-attachments/assets/6432cc4e-128f-4d76-95d3-9138b14f780c

The code can be found here https://github.com/mikavilpas/my-nvim-micro-plugins.nvim/blob/10cb4514a90449cf41c9281e009d9a4e48a27de0/lua/my-nvim-micro-plugins/multicursors.lua#L1-L75

I also implemented `A` to add to the end of each visual line.

**Comment by jake-stewart** [comment]
fixed in latest commit.

when i have time i will optimise match, select, and align. they currently read all lines in buffer.

**Comment by jake-stewart** [comment]
i notice you have extended multicursors functionality. i plan on making an api for lower level multicursor manipulation so people can easily write align/match/split functions. ill make a new issue about it and ping you

**Comment by mikavilpas** [comment]
That sounds cool, thanks!

**Comment by jake-stewart** [comment]
looks like i got the two issues mixed up. i have added `mc.visualToCursors()` for this.
