### ISSUE TITLE
Issue with multiline matchAllAddCursor 

### ISSUE THREAD

**Issue by ventsislav-georgiev** [jake-stewart/multicursor.nvim#61]
Having a visual selection on spanning more than one line doesn't work with mc.matchAllAddCursor.

Here is a video with the following list of operations:
1. `viw` + `mc.matchAllAddCursor()`
2. `vj` + `mc.matchAllAddCursor()` - fails, the cursor just jumps to begining of selection
3. `vj` + `mc.addCursor('*')` + `mc.addCursor('*')` - works, matching one by one

https://github.com/user-attachments/assets/d42bf414-8138-489b-a537-f8cd4da4f4b7

**Comment by jake-stewart** [comment]
fixed. try `:Lazy update` and let me know if any problems. thanks

**Comment by ventsislav-georgiev** [comment]
@jake-stewart That was fast! Thanks! Tested and working.

**Comment by jake-stewart** [comment]
@ventsislav-georgiev no worries. I just did another update which fixes an infinite loop when matchAddAll from middle of a word. So probably update again.
