### ISSUE TITLE
[Help] Compatibility with blink.cmp

### ISSUE THREAD

**Issue by Ajaymamtora** [jake-stewart/multicursor.nvim#66]
When using multiple cursors with https://github.com/Saghen/blink.cmp -- only the completion under the current cursor is filled in. I think there was a similar bug with nvim-cmp ?

**Comment by jake-stewart** [comment]
blink.cmp is not dot repeatable. try completing something and then pressing `.` from normal mode. it does not work. you should open an issue on blink.cmp

**Comment by jake-stewart** [comment]
https://github.com/Saghen/blink.cmp/pull/1033

#81

blink.cmp should work now!
