### ISSUE TITLE
CursorContext:getCursors typo for disabledCursors option

### ISSUE THREAD

**Issue by ajvondrak** [jake-stewart/multicursor.nvim#67]
The `disabledCursors` local is bound to the result of the `enabledCursors` option, so the `disabledCursors` option is not honored: https://github.com/jake-stewart/multicursor.nvim/blob/b715cc5bf69cf6e338899510eb2b60b1dd7ccce0/lua/multicursor-nvim/cursor-manager.lua#L842

**Comment by jake-stewart** [comment]
fixed. crazy it existed for so long
