### ISSUE TITLE
How to swap text regions

### ISSUE THREAD

**Issue by swarn** [jake-stewart/multicursor.nvim#68]
Hi Jake, nice plugin!

This isn't so much an "issue" as a question/feedback; please ignore/delete as desired. Maybe a wiki or discussions for the repo?

I'd like to implement `swapCursors`. Similar notion to the transpose function, but simply exchanges the selected region under the main cursor with an adjacent region. Also, I'd like it to work with multiple line selections. So given the following text
```
p1 text text
text

p2 text text

p3 text text
text
text
```
it would be easy to split into paragraphs, then reorder the paragraphs.

The `transpose` example is good, but only works with single lines. It seems like calling `nvim_buf_set_text` in an `mc.action` doesn't get repeated. So I thought I'd use a few registers. What I have is
```lua
local function swapCursors(direction)
  mc.action(function(ctx)
    local thisCursor = ctx:mainCursor()
    local thisPos = thisCursor:getPos()

    local otherCursor
    if direction == -1 then
      otherCursor = ctx:prevCursor(thisPos)
    else
      otherCursor = ctx:nextCursor(thisPos)
    end
    if not otherCursor then return end

    thisCursor:feedkeys([["zygv]])
    otherCursor:feedkeys([["yygv]])

    thisCursor:feedkeys('"yp`]v`[')
    otherCursor:feedkeys('"zp`]v`[')

    otherCursor:select()
  end)
end
```
This works the first time I call it, but has errors on multi-line selections _after_ the first time. I think this is something to do with restoring the visual selection at the cursor after the paste operation.

How about a `cursor:setLines()` method :).

**Comment by jake-stewart** [comment]
Hi swarn

there are no guidelines for issues/contributing because i find them annoying.

i've added `Cursor:setVisualLines(string[])` which does the job:

```lua
local thisLines = thisCursor:getVisualLines()
local otherLines = otherCursor:getVisualLines()

thisCursor:setVisualLines(otherLines)
otherCursor:setVisualLines(thisLines)
```

works very well for visual char and line mode. visual block mode needs some work but looks very complicated.

try `:Lazy update` and let me know if any issues.

**Comment by swarn** [comment]
Nice!

The API works well. This `swap` function is now very clean. Another example: I was happy to write a "run arbitrary Ex command at cursors" function and find that it is as simple as:
```lua
local function runCmdAtCursors(command)
  mc.action(function(ctx)
    command = command or vim.fn.input "Command: "
    if not command or command == "" then return end

    ctx:forEachCursor(function(cursor)
      cursor:perform(function() vim.cmd(command) end)
    end)
  end)
end
```

**Comment by swarn** [comment]
I should have tested more before commenting!

This works for selections on different lines, but not selections on the same line — which I know, I didn't mention earlier. Starting here:
<img width="177" src="https://github.com/user-attachments/assets/269b84e4-2e39-4755-96f1-85d5d07bc0a8">

Sometimes the result is this:
<img width="185" src="https://github.com/user-attachments/assets/aa68128c-d664-4341-be65-7303d2b25eac">

And somtimes it just throws an error:

    ...multicursor.nvim/lua/multicursor-nvim/cursor-manager.lua:1208: attempt to index field '_redoChangePos' (a nil value)

The code for the above is what you expect, but for the sake of completeness:
<details>
<summary>swapCursors code</summary>

```lua
local function swapCursors(direction)
  mc.action(function(ctx)
    local thisCursor = ctx:mainCursor()
    local thisPos = thisCursor:getPos()

    local otherCursor
    if direction == -1 then
      otherCursor = ctx:prevCursor(thisPos)
    else
      otherCursor = ctx:nextCursor(thisPos)
    end
    if not otherCursor then return end

    local thisLines = thisCursor:getVisualLines()
    local otherLines = otherCursor:getVisualLines()

    thisCursor:setVisualLines(otherLines)
    otherCursor:setVisualLines(thisLines)

    otherCursor:select()
  end)
end
```

</details>

I've come up with a contrived example that I think covers everything. Starting with the following text:
<img width="260" src="https://github.com/user-attachments/assets/752684f9-172f-416b-972f-592ae9610839">

You can select all, then match `(` to create cursors, then `vi)` (from mini-ai) to select inside parentheses including whitespace. By the way, I like how this plugin instantly works with custom textobjects.
<img width="254" src="https://github.com/user-attachments/assets/4cbadebc-b5f3-475b-bdd0-d11fced5ca61">

The `swap` function using the new `setVisualLines` method results in:
<img width="249" src="https://github.com/user-attachments/assets/93d4815d-5bd6-4c8e-93c6-509d83587d34">
The selection of the `222` region has vanished.

Instead we'd like to see:
<img width="214" src="https://github.com/user-attachments/assets/c99b54e9-c228-416a-8a43-97896a7e9ab9">

After two swaps back:
<img width="221" src="https://github.com/user-attachments/assets/55227788-f1fc-4e41-bb4c-9c6d769f37c4">

And this would be the result after three swaps:
<img width="250" src="https://github.com/user-attachments/assets/e474bb4e-a49e-42c7-879a-a0e53e296208">

The reason I'm hoping for this super-generalized behavior is that multicursor can generalize and replace a lot of "splitjoin" and [swap](https://github.com/nvim-treesitter/nvim-treesitter-textobjects?tab=readme-ov-file#text-objects-swap) functions.

**Comment by jake-stewart** [comment]
@swarn I have pushed out a new fix. try `:Lazy update`

Seems to work well for cursors on the same line. I also made undo/redo work properly. Let me know if any issues.

Glad you like the api. Since I wrote all the examples/default behaviours with the same api it is quite capable.

**Comment by swarn** [comment]
@jake-stewart, this looks good. It works for swapping the words in a line:
```
aaa bbb ccc
```
As well as paragraphs:
```
aaa aaa
aaaa

bbb

ccc
ccc
ccc
```

It still struggles with the contrived, mixed example above. Starting with
<img width="217" src="https://github.com/user-attachments/assets/1ef3f4e8-2333-436d-9bb2-8a50363f2c1c">

Selecting inside parens
<img width="249" src="https://github.com/user-attachments/assets/192b690a-51a1-48b7-bbb1-34659d531caa">

One swap backwards isn't quite right: it lost the trailing newline for the 4 block. Also, the 4 block selection now includes the leading paren.
<img width="176" src="https://github.com/user-attachments/assets/0af827a1-2bc0-4479-ace2-182211a55ed0">

Which we can see if we swap backwards again
<img width="201" src="https://github.com/user-attachments/assets/5dfceca3-aa62-4c5f-b780-1f6526775fbf">

Also, undo doesn't work properly after that second swap. It looks like this:
<img width="218" src="https://github.com/user-attachments/assets/07d89774-9407-4f20-b7a4-cb005eadfcb4">

**Comment by swarn** [comment]
💯 

It works for all the tests I can come up with.

I see you're feeding the lines into a register and pasting it, then restoring the register. Is the `feedkeys` approach better than trying to use `nvim_buf_set_text`? I tried to use the latter without success.

**Comment by jake-stewart** [comment]
by using `feedkeys`, i let vim handle how replacing a visual selection works. i
define pass `l`, `b` or `c` to `vim.fn.setreg` to define that the lines are
line/block/char. in contrast to `nvim_buf_set_text`, i would need to call it
per each line of a visual block selection. replacing a visual selection with
`P` automatically sets the change marks which i use to set the new cursor
position and visual selection.

it would be very tricky with `nvim_buf_set_text` since i would need to manually
calculate the new visual selection. for visual char mode, the visual end column
is the length of the last line, unless the visual selection spans one line then
it is the visual start column + length of the last line. similar edge cases
exist for the other visual modes.

also `nvim_buf_set_text` does not allow including the eol character in a range
since it is considered "out of range". i would need to handle this case by
decreasing the end line by one and setting end column to zero.

**Comment by swarn** [comment]
Ah, it makes to use `P` and let vim handle the bookkeeping for you. Thanks for explaining!

**Comment by jake-stewart** [comment]
@swarn i have added `swapCursors` to the examples.

sidenote, i added `seekCursor` and `seekBoundaryCursor`, which simplifies the code a little bit more.

```lua
--- @param direction -1 | 1
--- @param wrap? boolean
function examples.swapCursors(direction, wrap)
    mc.action(function(ctx)
        local mainCursor = ctx:mainCursor()
        local otherCursor = ctx:seekCursor(
            mainCursor:getPos(), direction, wrap)
        if otherCursor and otherCursor ~= mainCursor then
            local mainLines = mainCursor:getVisualLines()
            local otherLines = otherCursor:getVisualLines()
            mainCursor:setVisualLines(otherLines)
            otherCursor:setVisualLines(mainLines)
            otherCursor:select()
        end
    end)
end
```
