### ISSUE TITLE
Wanted: option to disable wrapping in mc.{prev,next}Cursor

### ISSUE THREAD

**Issue by ajvondrak** [jake-stewart/multicursor.nvim#71]
I was gonna make this suggestion after clearing up #69, but it seems that you might be a step ahead of me with the [`CursorContext:seekCursor` refactor](https://github.com/jake-stewart/multicursor.nvim/blob/7b2be6ed76c1a104fb0b1d82fb5f83f4e8c24198/lua/multicursor-nvim/cursor-manager.lua#L955). :)

But basically, I was going to point out that it's not so easy to disable the wrapping from the `mc.{prev,next}Cursor` mappings, which are now made more complex by handling the enabled/disabled cursors. So it would be convenient to be able to pass something in so that the `true`s hard-coded in https://github.com/jake-stewart/multicursor.nvim/blob/7b2be6ed76c1a104fb0b1d82fb5f83f4e8c24198/lua/multicursor-nvim/examples.lua#L430 and https://github.com/jake-stewart/multicursor.nvim/blob/7b2be6ed76c1a104fb0b1d82fb5f83f4e8c24198/lua/multicursor-nvim/examples.lua#L436 could be overridden. In the end, I'm imagining being able to do something like

```lua
vim.keymap.set("n", "<right>", function() mc.nextCursor({ wrap = false }) end)
vim.keymap.set("n", "<left>", function() mc.prevCursor({ wrap = false }) end)
```

Existing mappings like `vim.keymap.set("n", "<right>", mc.nextCursor)` could remain backwards compatible by defaulting the opts to `wrap = true`.

**Comment by jake-stewart** [comment]
@ajvondrak I think I'd rather have `wrap` as a regular param, instead of an options dict.

So you would do `mc.nextCursor(false)` to disable wrapping. if the `wrap` parameter is `nil`, then it can default to `true`.

**Comment by jake-stewart** [comment]
sorted

**Comment by ajvondrak** [comment]
Works for me. Thanks!
