### ISSUE TITLE
Compatibility with blink.cmp

### ISSUE THREAD

**Issue by aaronlifton** [jake-stewart/multicursor.nvim#74]
This plugin works perfectly with multiple cursors with nvim-cmp - I select a completion item, and it is completed at each cursor without issue. This is truly an amazing feature.

However, after switching to blink.cmp, this no longer works and only the current cursor is completed. That means I have to type everything manually without using completion. I hope this is fixable!

Here is a video - note how `collectgarbage` is only completed at the current line, and the rest of the lines now have `clecollectgarbage`. This is happening with blink.cmp, but works fine with nvim-cmp.

https://github.com/user-attachments/assets/8dc25458-5db2-4c2a-b85c-b0dd4137f16f

**Comment by jake-stewart** [comment]
https://github.com/jake-stewart/multicursor.nvim/issues/66

Unfortunately this is a blink.nvim bug. It does not support dot repeat. Try completing an item and then pressing `.` from normal mode. It does not work.

There is already an issue open on blink.nvim: https://github.com/Saghen/blink.cmp/issues/182

Workaround is to use nvim-cmp. It works well as you've pointed out.

**Comment by jake-stewart** [comment]
https://github.com/Saghen/blink.cmp/pull/870

**Comment by jake-stewart** [comment]
https://github.com/Saghen/blink.cmp/pull/1033

#81

blink.cmp should work now!
