### ISSUE TITLE
Error when editing with multiple cursors

### ISSUE THREAD

**Issue by jsongerber** [jake-stewart/multicursor.nvim#9]
I just installed this plugin to test it and it looks promising, thanks for your work!

I copy pasted the readme config and have a few issues.

When I add cursor using `mc.addCursor` it works when I edit buffer with `a` or `i`, but as soon as I exit insert mode with `<esc>` I get this error:
```
Error detected while processing SafeState Autocommands for "*":
Error executing lua callback: ...multicursor.nvim/lua/multicursor-nvim/cursor-manager.lua:1022: attempt to call field 'unpack' (a nil value)
stack traceback:
        ...multicursor.nvim/lua/multicursor-nvim/cursor-manager.lua:1022: in function 'callback'
        .../nvim/lazy/multicursor.nvim/lua/multicursor-nvim/tbl.lua:24: in function 'map'
        ...multicursor.nvim/lua/multicursor-nvim/cursor-manager.lua:1061: in function 'cursorContextUpdate'
        ...multicursor.nvim/lua/multicursor-nvim/cursor-manager.lua:1164: in function 'action'
        .../multicursor.nvim/lua/multicursor-nvim/input-manager.lua:131: in function '_onSafeState'
        .../multicursor.nvim/lua/multicursor-nvim/input-manager.lua:39: in function <.../multicursor.nvim/lua/multicursor-nvim/input-manager.lua:38>
```
It also produce the same error if I use visual mode with multiple cursors and try to delete it with `d`.
The edit is still working as soon as I disregard the error.

Also, and tell me if you want a different issue, but exiting multiple cursor mode doesn't clear the other cursor highlights, and theres "ghost" cursor still in the buffer.

I'm using Mac OS with
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128
Run "nvim -V1 -v" for more info

**Comment by jake-stewart** [comment]
the error should be fixed now. try `:Lazy update`.

does the ghost issue occur only when it crashes? Possibly it is fixed along with the first one. Let me know how it goes, thanks.

**Comment by jsongerber** [comment]
That was quick, it now works thank you.
You can ignore the ghost issue, it was a combinaison of me that didn't understand the `disableCursors` and my `<esc>` key that was remapped by my lsp config.

**Comment by jake-stewart** [comment]
Thanks for opening the issue
